[tool.poetry]
name = "eodc-cluster-image"
version = "1.0.0"
description = ""
authors = ["Tobias Stachl <tobias.stachl@eodc.eu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
eodc = "^2024.8.1"
dask-gateway = "^2023.8.0"
# Dask minimum 2024.4.1. 2024.4.0 breaks on Python 3.11.9!
dask = {extras = ["array", "dataframe", "distributed"], version = "<=2024.5.2"}
rioxarray = "^0.17.0"
odc-stac = "^0.3.10"
xarray = "^2024.11.0"
zarr = "^2.18.4"
bokeh = "^3.6.3"
stactools = "^0.5.3"
pystac = "<=1.12.1"
pystac-client = "^0.8.5"
pytileproj = "^0.0.17"
numpy = "<2"
scipy = "<=1.15.1"
shapely = "<=2.0.7"
rasterio = "<=1.4.3"
netcdf4 = "<=1.7.2"
h5netcdf = "<=1.5.0"
odc-geo = "<=0.4.9.post0"
odc-stac = "<=0.3.3"
pandas = "<=2.2.3"
pyproj = "<=3.7.0"
lz4 = "^4.4.3"
requests = "^2.32.3"
zarr = "2.18.0"
xarray = "<=2025.1.2"
s3fs = "<=2025.2.0"
dask = {extras = ["array", "core", "distributed"], version = "2022.10.2"}
dask-gateway = "<=2024.1.0"
botocore = "1.35.88"
fsspec = "^2025.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
